// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TigerPawCodeAPI.Models;

namespace TigerPawCodeAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20190123082411_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TigerPawCodeAPI.Models.Blog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Author");

                    b.Property<string>("Content");

                    b.Property<DateTime>("DateCreated");

                    b.Property<DateTime?>("DateDeleted");

                    b.Property<DateTime?>("DateLive");

                    b.Property<int>("EstimatedReadingTime");

                    b.Property<string>("Headline");

                    b.Property<bool>("Promoted");

                    b.Property<string>("ShortDescription");

                    b.Property<int>("Status");

                    b.Property<string>("Thumbnail");

                    b.HasKey("Id");

                    b.ToTable("Blogs");

                    b.HasData(
                        new { Id = 1, Author = "Adam Bakal", Content = @"
    <p>Loads of content.</p>
    <p>And stuff.</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc placerat, ligula vitae viverra blandit,
    orci mauris vestibulum urna, in elementum urna felis posuere orci. Sed sed eros a purus euismod lacinia
     vitae sit amet nisi. Suspendisse potenti. Duis aliquam nec ipsum id commodo.
     Vivamus rutrum sem sit amet ligula interdum sagittis. In a tortor eros. In ac neque ante.
      Donec aliquet orci augue, vitae accumsan nulla ultrices id. Vivamus sagittis eu mi eget consequat.
      Integer commodo, sem vitae tristique convallis, felis nunc ornare augue, nec hendrerit
      tellus nibh sit amet augue. Phasellus erat elit, tempus ac suscipit non, luctus et ipsum. Etiam dictum,
       nibh eget elementum sollicitudin, libero justo cursus leo, sit amet fermentum dolor nisl eu est. Aenean
       elementum pretium justo vitae elementum. Aenean vel velit sem.
     Etiam hendrerit in est ut mattis.</p>
     <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc placerat, ligula vitae viverra blandit,
     orci mauris vestibulum urna, in elementum urna felis posuere orci. Sed sed eros a purus euismod lacinia
      vitae sit amet nisi. Suspendisse potenti. Duis aliquam nec ipsum id commodo.
      Vivamus rutrum sem sit amet ligula interdum sagittis. In a tortor eros. In ac neque ante.
       Donec aliquet orci augue, vitae accumsan nulla ultrices id. Vivamus sagittis eu mi eget consequat.
       Integer commodo, sem vitae tristique convallis, felis nunc ornare augue, nec hendrerit
       tellus nibh sit amet augue. Phasellus erat elit, tempus ac suscipit non, luctus et ipsum. Etiam dictum,
        nibh eget elementum sollicitudin, libero justo cursus leo, sit amet fermentum dolor nisl eu est. Aenean
        elementum pretium justo vitae elementum. Aenean vel velit sem.
      Etiam hendrerit in est ut mattis.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc placerat, ligula vitae viverra blandit,
      orci mauris vestibulum urna, in elementum urna felis posuere orci. Sed sed eros a purus euismod lacinia
       vitae sit amet nisi. Suspendisse potenti. Duis aliquam nec ipsum id commodo.
       Vivamus rutrum sem sit amet ligula interdum sagittis. In a tortor eros. In ac neque ante.
        Donec aliquet orci augue, vitae accumsan nulla ultrices id. Vivamus sagittis eu mi eget consequat.
        Integer commodo, sem vitae tristique convallis, felis nunc ornare augue, nec hendrerit
        tellus nibh sit amet augue. Phasellus erat elit, tempus ac suscipit non, luctus et ipsum. Etiam dictum,
         nibh eget elementum sollicitudin, libero justo cursus leo, sit amet fermentum dolor nisl eu est. Aenean
         elementum pretium justo vitae elementum. Aenean vel velit sem.
       Etiam hendrerit in est ut mattis.</p>
       <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc placerat, ligula vitae viverra blandit,
       orci mauris vestibulum urna, in elementum urna felis posuere orci. Sed sed eros a purus euismod lacinia
        vitae sit amet nisi. Suspendisse potenti. Duis aliquam nec ipsum id commodo.
        Vivamus rutrum sem sit amet ligula interdum sagittis. In a tortor eros. In ac neque ante.
         Donec aliquet orci augue, vitae accumsan nulla ultrices id. Vivamus sagittis eu mi eget consequat.
         Integer commodo, sem vitae tristique convallis, felis nunc ornare augue, nec hendrerit
         tellus nibh sit amet augue. Phasellus erat elit, tempus ac suscipit non, luctus et ipsum. Etiam dictum,
          nibh eget elementum sollicitudin, libero justo cursus leo, sit amet fermentum dolor nisl eu est. Aenean
          elementum pretium justo vitae elementum. Aenean vel velit sem.
        Etiam hendrerit in est ut mattis.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc placerat, ligula vitae viverra blandit,
        orci mauris vestibulum urna, in elementum urna felis posuere orci. Sed sed eros a purus euismod lacinia
         vitae sit amet nisi. Suspendisse potenti. Duis aliquam nec ipsum id commodo.
         Vivamus rutrum sem sit amet ligula interdum sagittis. In a tortor eros. In ac neque ante.
          Donec aliquet orci augue, vitae accumsan nulla ultrices id. Vivamus sagittis eu mi eget consequat.
          Integer commodo, sem vitae tristique convallis, felis nunc ornare augue, nec hendrerit
          tellus nibh sit amet augue. Phasellus erat elit, tempus ac suscipit non, luctus et ipsum. Etiam dictum,
           nibh eget elementum sollicitudin, libero justo cursus leo, sit amet fermentum dolor nisl eu est. Aenean
           elementum pretium justo vitae elementum. Aenean vel velit sem.
         Etiam hendrerit in est ut mattis.</p>
", DateCreated = new DateTime(2019, 1, 23, 8, 24, 11, 634, DateTimeKind.Local), DateLive = new DateTime(2019, 1, 23, 8, 24, 11, 640, DateTimeKind.Local), EstimatedReadingTime = 10, Headline = "Working with Angular", Promoted = false, ShortDescription = "Tips on working with Angular", Status = 1, Thumbnail = "https = //www.fillmurray.com/g/140/100" }
                    );
                });

            modelBuilder.Entity("TigerPawCodeAPI.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Admin");

                    b.Property<DateTime>("RoleCreated");

                    b.Property<DateTime?>("RoleDeleted");

                    b.Property<string>("RoleName");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("TigerPawCodeAPI.Models.Subscriber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateSubscribed");

                    b.Property<DateTime?>("DateUnsubscribed");

                    b.Property<string>("Email");

                    b.HasKey("Id");

                    b.ToTable("Subscribers");
                });

            modelBuilder.Entity("TigerPawCodeAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateCreated");

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<DateTime>("LastModified");

                    b.Property<string>("LastName");

                    b.Property<string>("Password");

                    b.Property<byte[]>("PasswordHash");

                    b.Property<byte[]>("PasswordSalt");

                    b.Property<int?>("RoleId");

                    b.Property<bool>("Subscribed");

                    b.Property<DateTime?>("UserDeleted");

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TigerPawCodeAPI.Models.User", b =>
                {
                    b.HasOne("TigerPawCodeAPI.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId");
                });
#pragma warning restore 612, 618
        }
    }
}
